import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientLayout from "./clientlayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "DjangoBnB",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  const Content=[
    <p>Hello world</p>
  ]
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="">
        <ClientLayout>{children}</ClientLayout>
      </div>
      </body>
    </html>
  );
}
